artifacts_root: artifacts

ingestion_data:
  root_dir: artifacts/ingestion_data
  email_dir: data/emails
  pdf_dir: data/pdf
  csv_dir: data/spreadsheets
  db_path: data/sql/small.db
  output_json: artifacts/ingestion_data/output.json

transform_data:
  input_json: artifacts/ingestion_data/output.json

  entities_output: artifacts/transform_data/entities.json
  relationships_output: artifacts/transform_data/relationships.json
  triples_output: artifacts/transform_data/triples.json

  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: "12345678"

pipeline_embedd:
  input_json: artifacts/ingestion_data/output.json

  chunking:
    chunk_size: 100
    chunk_overlap: 40

  embedding_model:
    name: sentence-transformers/all-MiniLM-L6-v2
    embedding_dim: 384

  vector_store:
    type: faiss
    index_type: IndexFlatL2
    index_path: artifacts/embeddings/faiss.index
    metadata_path: artifacts/embeddings/metadata.json

rag:
  input_json: artifacts/ingestion_data/output.json

  faiss:
    index_path: artifacts/embeddings/faiss.index
    metadata_path: artifacts/embeddings/metadata.json
    top_k: 5

  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: "12345678"

  llm:
    provider: groq
    model: llama-3.1-8b-instant
    temperature: 0.35
    max_tokens: 1024
